#!/usr/bin/env node
/**
 * Generate docs/tool-catalogue.md FROM THE REAL SURFACE.
 *
 * The catalogue has now been wrong twice. The first time the counts were
 * hand-written and simply incorrect; the second time it was generated
 * correctly and then went stale, because the OpenAI provider was added in
 * a later commit and nobody re-ran anything. Seventeen tools — an entire
 * provider — were missing from a document whose whole purpose is to say
 * what the server exposes.
 *
 * So the generator lives in `scripts/`, `npm run catalogue` produces the
 * file, and `npm run catalogue:check` fails the build when the committed
 * document no longer matches the source. A document that can go stale
 * silently is a document that will.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');

const { buildProviders } = await import(join(root, 'dist/providers/index.js'));
const { platformTools } = await import(join(root, 'dist/platform/tools.js'));
const { workflowTools } = await import(join(root, 'dist/workflows/tools.js'));
const { loadConfig } = await import(join(root, 'dist/config.js'));

/*
 * Every provider is configured with a placeholder credential, because the
 * catalogue must describe the WHOLE surface — not the subset that happens
 * to be configured on the machine that ran the generator. That is exactly
 * how a provider goes missing from it.
 */
const env = Object.fromEntries(
  [
    'CLOUDFLARE_API_TOKEN', 'GITHUB_TOKEN', 'NEON_API_KEY', 'VERCEL_TOKEN',
    'CLERK_SECRET_KEY', 'RESEND_API_KEY', 'BREVO_API_KEY', 'OPENAI_API_KEY',
  ].map((name) => [name, 'catalogue-placeholder-value']),
);

const config = loadConfig({ env });
const providers = buildProviders({ config });
const tools = [
  ...providers.tools,
  ...platformTools({ config, active: providers.active, version: '(catalogue)' }),
  ...workflowTools({ tools: new Map(), contextFor: () => ({}), active: providers.active, now: () => new Date(0) }),
];

const CLASSES = ['read', 'write', 'protected'];
const byProvider = new Map();
for (const tool of tools) {
  const key = tool.provider === 'stromex' ? 'stromex' : tool.provider;
  if (!byProvider.has(key)) byProvider.set(key, []);
  byProvider.get(key).push(tool);
}

const count = (list, cls) => list.filter((t) => t.operationClass === cls).length;
const totals = Object.fromEntries(CLASSES.map((c) => [c, count(tools, c)]));

const providerRows = [...byProvider.entries()]
  .sort((a, b) => b[1].length - a[1].length || a[0].localeCompare(b[0]))
  .map(([name, list]) =>
    `| \`${name}\` | ${list.length} | ${count(list, 'read')} | ${count(list, 'write')} | ${count(list, 'protected')} |`)
  .join('\n');

const protectedList = tools
  .filter((t) => t.operationClass === 'protected')
  .sort((a, b) => a.name.localeCompare(b.name))
  .map((t) => `- \`${t.name}\``)
  .join('\n');

const spending = tools.filter((t) => typeof t.purchase === 'function').map((t) => `\`${t.name}\``);
const secretBearing = tools.filter((t) => t.secretArgs?.length).map((t) => `\`${t.name}\``);

const table = [...byProvider.entries()]
  .sort((a, b) => a[0].localeCompare(b[0]))
  .map(([name, list]) => {
    const rows = list
      .slice()
      .sort((a, b) => a.name.localeCompare(b.name))
      .map((t) => `| \`${t.name}\` | ${t.operationClass} | ${t.title} |`)
      .join('\n');
    return `### ${name}\n\n| Tool | Class | Title |\n|---|---|---|\n${rows}\n`;
  })
  .join('\n');

const doc = `# Tool catalogue

**Generated by \`npm run catalogue\` from the real surface. Do not edit by
hand.** \`npm run catalogue:check\` fails when this file and the source
disagree — which is how the entire OpenAI provider came to be missing from
it for a release (\`SEB-D 29\`).

**${tools.length} tools** across **${byProvider.size} providers**:
**${totals.read} read**, **${totals.write} write**, **${totals.protected} protected**.

| Provider | Tools | read | write | protected |
|---|---|---|---|---|
${providerRows}
| **total** | **${tools.length}** | **${totals.read}** | **${totals.write}** | **${totals.protected}** |

## The protected operations

Every one requires an explicit approval bound to the exact arguments, and
captures a pre-image first. There are **${tools.filter((t) => t.operationClass === 'protected').length}**.

${protectedList}

## The tools that spend money

Declared purchases, gated by the spending policy before the provider is
called: ${spending.length ? spending.join(', ') : '_none_'}.

**Metered spend is not in this list and is not a declared purchase.** The
sixteen \`openai.*\` consultations bill by the token and are bound by
\`ctx.assertSpendHeadroom\` and the rolling cap rather than by a
per-purchase limit, because a metered call has no price until it has been
made (\`SEB-D 29\`).

## The tools that accept a literal secret

Their \`value\` argument is masked out of the audit record structurally,
because it is declared here: ${secretBearing.length ? secretBearing.join(', ') : '_none_'}.
Prefer \`valueFromHandle\` in every case (\`SEB-D 31\`).

## Every tool

${table}`;

const path = join(root, 'docs/tool-catalogue.md');

if (check) {
  const current = await readFile(path, 'utf8').catch(() => '');
  if (current.trim() !== doc.trim()) {
    console.error('✗ docs/tool-catalogue.md is out of date with the source. Run `npm run catalogue`.');
    process.exit(1);
  }
  console.log(`✓ tool catalogue matches the source — ${tools.length} tools across ${byProvider.size} providers`);
  process.exit(0);
}

await writeFile(path, doc, 'utf8');
console.log(`catalogue: ${tools.length} tools across ${byProvider.size} providers (${totals.read} read, ${totals.write} write, ${totals.protected} protected)`);
