// The 22 generated pages match their sources.
//
// The site is assembled by `scripts/build.js` from `pages/*.html` plus
// `partials/`, and the OUTPUT is committed — Cloudflare Pages serves the
// repository root directly, so the built files have to be in git. That
// is a legitimate deployment choice with one sharp edge: the repository
// now contains two copies of every marketing page, and nothing notices
// when they disagree.
//
// The failure is quiet and one-directional. Someone fixes a typo in
// `about/index.html` — the file whose path matches the URL, and the
// obvious one to open. It looks correct, it reviews correctly, it even
// deploys correctly once. Then the next build regenerates that file from
// `pages/about.html`, which never had the fix, and the typo returns with
// no diff, no error and nobody able to explain it.
//
// CI already runs `npm run build`, which means CI was actively hiding
// this: it rebuilt over the hand edit in the runner, tested the
// regenerated file, and passed.
//
// This test builds and compares. It restores whatever it found before
// reporting, so a failing run leaves the working tree exactly as it was.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { ROOT } from './helpers.mjs';

let pass = 0, fail = 0;
const check = (label, cond, detail) => {
  console.log((cond ? 'PASS ' : 'FAIL ') + label + (cond || detail === undefined ? '' : ` — ${detail}`));
  cond ? pass++ : fail++;
};

const manifest = JSON.parse(readFileSync(path.join(ROOT, 'pages/manifest.json'), 'utf8'));
check('The manifest lists the pages to generate', manifest.length >= 20, `${manifest.length} pages`);

// Snapshot what is committed, so the build can be compared against it
// and the tree put back either way.
const before = new Map();
const missing = [];
for (const page of manifest) {
  const full = path.join(ROOT, page.output);
  if (!existsSync(full)) { missing.push(page.output); continue; }
  before.set(page.output, readFileSync(full, 'utf8'));
}
check('Every manifest entry has a generated file committed', missing.length === 0, missing.join(', '));

execFileSync(process.execPath, [path.join(ROOT, 'scripts/build.js')], { cwd: ROOT, stdio: 'pipe' });

// THE BUILD STAMP IS EXCLUDED FROM THIS COMPARISON, DELIBERATELY.
//
// Every page carries <meta name="wec-build"> holding the commit it was
// generated from, so a deploy can be proven against the live domain
// rather than assumed (see the workflow's proof step). That value is by
// definition a function of the COMMIT, not of the source — so the
// committed output can never equal a fresh rebuild, and this test would
// fail on all 64 pages forever while nothing was actually wrong.
//
// The invariant this file exists to protect is "the served pages are
// what pages/ produces". Normalising one self-referential meta tag
// keeps that invariant exact for every other byte, which is the whole
// of what it is for. Stripping more than this line would start hiding
// real drift, so it strips exactly this line.
const unstamp = (html) =>
  html.replace(/<meta name="wec-build" content="[^"]*">/g, '<meta name="wec-build">');

const drifted = [];
for (const page of manifest) {
  const full = path.join(ROOT, page.output);
  const after = existsSync(full) ? readFileSync(full, 'utf8') : null;
  if (before.has(page.output) && unstamp(after) !== unstamp(before.get(page.output))) {
    drifted.push(page.output);
    writeFileSync(full, before.get(page.output));   // leave the tree as found
  }
}

check('No generated page differs from what its source produces',
  drifted.length === 0,
  drifted.length
    ? `edited directly instead of in pages/: ${drifted.join(', ')} — the next build would discard those changes`
    : undefined);

// The other direction: a source with no output is a page somebody wrote
// and nobody can reach. It fails the same way a broken link does, except
// there is no link to notice is broken.
const outputs = new Set(manifest.map((p) => p.contentFile));
const orphans = [];
for (const f of (await import('node:fs')).readdirSync(path.join(ROOT, 'pages'))) {
  if (!f.endsWith('.html')) continue;
  if (!outputs.has(f)) orphans.push(f);
}
check('Every page source is reachable through the manifest', orphans.length === 0,
  orphans.length ? `${orphans.join(', ')} — authored but never built, so never served` : undefined);

// ---------------------------------------------------------------------
// THE MASTHEAD REACHES EVERY PAGE IT SHOULD
//
// css/pages.css turns a page's opening section into a masthead, but only
// when that section carries .page-hero. The class was first added by
// editing the files in pages/ directly — which was invisible breakage,
// because most of those files are generated by the cluster scripts
// (build-students.js, build-about.js, build-press.js, build-arabic.js
// and the rest). Running any generator stripped the class straight back
// out. The build succeeded, every test passed, and the page silently
// lost its masthead.
//
// scripts/build.js now applies it at assembly instead, so it survives
// every generator. This is the check that says so — and that catches the
// day someone reintroduces the shortcut, or writes a page whose opening
// section does not match the shape the transform recognises.
// ---------------------------------------------------------------------
{
  // The homepage has its own bespoke hero; the portal pages open with a
  // sign-in shell rather than a masthead. Everything else gets one.
  const EXEMPT = new Set(['index.html', 'ar/index.html',
    'student-portal/index.html', 'ar/student-portal/index.html']);

  const missing = [];
  for (const page of manifest) {
    if (EXEMPT.has(page.output)) continue;
    const full = path.join(ROOT, page.output);
    if (!existsSync(full)) continue;
    if (!readFileSync(full, 'utf8').includes('class="page-hero')) missing.push(page.output);
  }
  check(`Every built page opens with a masthead — ${manifest.length - EXEMPT.size} expected`,
    missing.length === 0,
    missing.length
      ? `no .page-hero on: ${missing.slice(0, 6).join(', ')}${missing.length > 6 ? ` … +${missing.length - 6}` : ''}`
      : undefined);

  // And the homepage must NOT have acquired one, which would mean the
  // transform had started matching a shape it should leave alone.
  const home = path.join(ROOT, 'index.html');
  check('...and the homepage keeps its own hero rather than the shared one',
    !existsSync(home) || !readFileSync(home, 'utf8').includes('class="page-hero'));
}

console.log(`\n${pass} passed, ${fail} failed.`);
process.exit(fail ? 1 : 0);
