// THE FILES THAT DESCRIBE THE SITE TO SOMETHING THAT IS NOT A PERSON.
//
// A crawler, a browser and a CDN each read a file that claims to
// describe this site: sitemap.xml, the hrefs in every page, and
// _headers/_redirects. None of those has a reader who would notice when
// it stopped being true.
//
// sitemap.xml is the proof. It was written by hand and listed 20 URLs
// while the build produced 76 pages. Fifty-six published pages were
// invisible to any crawler that trusted it. Nothing failed. No test
// covered it. It simply stopped describing the site, and would have
// gone on doing so indefinitely.
//
// So this file checks the three of them against what the build actually
// produces, rather than against a second hand-written list — which
// would be a third thing that could drift.
import { readFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { ROOT } from './helpers.mjs';

let pass = 0, fail = 0;
const check = (label, cond, detail) => {
  console.log((cond ? 'PASS ' : 'FAIL ') + label + (cond || detail === undefined ? '' : ` — ${detail}`));
  cond ? pass++ : fail++;
};

const manifest = JSON.parse(readFileSync(path.join(ROOT, 'pages/manifest.json'), 'utf8'));
const entries = Array.isArray(manifest) ? manifest : manifest.pages;
const SITE = 'https://www.worldwencollege.co.uk';
const urlFor = (output) => '/' + output.replace(/index\.html$/, '');

// ---------------------------------------------------------------------
// 1 · THE SITEMAP LISTS EVERY PAGE THE BUILD PRODUCES
// ---------------------------------------------------------------------
const sitemap = readFileSync(path.join(ROOT, 'sitemap.xml'), 'utf8');
const listed = new Set([...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]));
const indexable = entries.filter((e) => !/(^|\/)404\.html$/.test(e.output));
const expected = new Set(indexable.map((e) => SITE + urlFor(e.output)));

const missing = [...expected].filter((u) => !listed.has(u));
const extra = [...listed].filter((u) => !expected.has(u));

check(`The sitemap lists every built page — ${listed.size} listed, ${expected.size} built`,
  missing.length === 0, `missing ${missing.length}: ${missing.slice(0, 4).join(', ')}`);
check('...and lists nothing that is not built',
  extra.length === 0, `stale ${extra.length}: ${extra.slice(0, 4).join(', ')}`);
check('The sitemap does not offer the error page for indexing',
  ![...listed].some((u) => /404/.test(u)));
check('The sitemap declares itself generated, so nobody edits it by hand',
  /Generated by scripts\/build\.js/.test(sitemap));
check('robots.txt points at the sitemap',
  /Sitemap:\s*https:\/\/www\.worldwencollege\.co\.uk\/sitemap\.xml/.test(
    readFileSync(path.join(ROOT, 'robots.txt'), 'utf8')));

// A check that only ever sees a correct sitemap proves nothing about
// its own reach. Confirm it catches the exact regression it exists for.
{
  const truncated = sitemap.split('\n').slice(0, 8).join('\n');
  const shortList = new Set([...truncated.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]));
  check('...and this check does catch a sitemap that has fallen behind the build',
    [...expected].some((u) => !shortList.has(u)));
}

// ---------------------------------------------------------------------
// 2 · EVERY INTERNAL LINK RESOLVES TO SOMETHING THE BUILD WROTE
// ---------------------------------------------------------------------
// Fifty-four pages were written in one stretch, cross-linking each
// other by hand. A single mistyped href is a dead end that nobody finds
// until a reader does.
const built = new Set(entries.map((e) => urlFor(e.output)));
// Not every served page is a manifest entry. The standalone
// application pages (my-programme.html, the Listening Lab, verify) are
// files at the repository root, and the design previews are directories
// the build does not write. Rather than keeping a hand-written list of
// exceptions — which is exactly the kind of list that goes stale — ask
// the filesystem what would actually be served.
//
// The directories the deploy withholds are excluded, so a link into
// docs/ or sql/ still counts as broken: it exists here and 404s in
// production, which is the worst of both.
const WITHHELD = /^\/(docs|tests|sql|scripts|publication|node_modules|partials|pages)\//;
const servedOnDisk = (target) => {
  if (WITHHELD.test(target)) return false;
  const rel = target.replace(/^\//, '');
  if (rel && existsSync(path.join(ROOT, rel)) && !target.endsWith('/')) return true;
  return existsSync(path.join(ROOT, rel, 'index.html'));
};

const broken = [];
let linksChecked = 0;
for (const e of entries) {
  const src = path.join(ROOT, 'pages', e.contentFile);
  if (!existsSync(src)) { broken.push({ page: e.contentFile, href: '(content file missing)' }); continue; }
  const html = readFileSync(src, 'utf8');
  for (const m of html.matchAll(/href="([^"]+)"/g)) {
    const raw = m[1];
    if (!raw.startsWith('/')) continue;              // external, mailto, anchor-only
    const target = raw.split('#')[0].split('?')[0];
    if (!target) continue;                            // bare '#'
    if (/^\/(css|js|assets|api)\//.test(target)) continue;
    linksChecked++;
    if (!built.has(target) && !servedOnDisk(target)) broken.push({ page: e.contentFile, href: target });
  }
}
check(`Every internal link resolves to a built page — ${linksChecked} links checked`,
  broken.length === 0,
  broken.slice(0, 6).map((b) => `${b.page} → ${b.href}`).join(' · '));

// The partials link too, and they appear on every page, so a broken
// href there is broken 76 times.
for (const partial of ['header.html', 'footer.html', 'topbar.html']) {
  const p = path.join(ROOT, 'partials', partial);
  if (!existsSync(p)) continue;
  const bad = [...readFileSync(p, 'utf8').matchAll(/href="(\/[^"#?]*)/g)]
    .map((m) => m[1])
    .filter((t) => t && !/^\/(css|js|assets|api)\//.test(t) && !built.has(t) && !servedOnDisk(t));
  check(`Every link in partials/${partial} resolves`, bad.length === 0, bad.join(', '));
}

// ---------------------------------------------------------------------
// 3 · THE HEADERS AND REDIRECTS SAY WHAT THEY CLAIM TO
// ---------------------------------------------------------------------
const headers = readFileSync(path.join(ROOT, '_headers'), 'utf8');
for (const h of ['X-Content-Type-Options: nosniff', 'X-Frame-Options: DENY',
  'Referrer-Policy: strict-origin-when-cross-origin', 'Strict-Transport-Security',
  'Cross-Origin-Opener-Policy: same-origin-allow-popups']) {
  check(`_headers sends ${h.split(':')[0]}`, headers.includes(h));
}
// The one that is not boilerplate: the Listening Lab records the
// learner, so a Permissions-Policy that denied the microphone would
// break the most distinctive part of the programme while looking
// responsible.
check('Permissions-Policy grants the microphone to this origin — the Listening Lab needs it',
  /Permissions-Policy:[^\n]*microphone=\(self\)/.test(headers));
check('...and denies camera and geolocation, which nothing here uses',
  /camera=\(\)/.test(headers) && /geolocation=\(\)/.test(headers));
// Absence stated rather than silently omitted.
check('The absence of a Content-Security-Policy is explained, not hidden',
  /Content-Security-Policy/.test(headers) && /sign-in/.test(headers));

const redirects = readFileSync(path.join(ROOT, '_redirects'), 'utf8');
check('The apex redirects to the canonical www host',
  /^https:\/\/worldwencollege\.co\.uk\/\*\s+https:\/\/www\.worldwencollege\.co\.uk\/:splat\s+301!/m.test(redirects));
check('...to the same host the canonical URLs use',
  sitemap.includes(SITE) && redirects.includes(SITE));
// A wildcard here would drop the credential code and render an empty
// verification page, which looks like a check that ran and passed.
check('No wildcard redirect can swallow a verification code',
  !/^\/verify\/\*/m.test(redirects));

console.log(`\n${pass} passed, ${fail} failed.`);
process.exit(fail ? 1 : 0);
