/**
 * THE TYPEFACES, FETCHED ONCE AND EMBEDDED.
 *
 * ────────────────────────────────────────────────────────────────────
 * WHY THIS EXISTS, AND IT IS THE ROOT CAUSE OF A LOT
 * ────────────────────────────────────────────────────────────────────
 * The publication specified `Cambria, "Nimbus Roman", Georgia, "Times
 * New Roman", serif` and `Calibri, "Segoe UI", Arial, sans-serif`.
 * NONE of those exist on the machine that renders it. Every page of
 * every version was set in whatever the fallback happened to be — a
 * Times metric clone — while the CSS described a document nobody had
 * ever seen. No amount of layout work reaches a flagship standard on
 * a typeface nobody chose.
 *
 * Four faces are fetched here, subset to latin, and written into the
 * repository as base64 so the render is deterministic and works with
 * no network at all. All four are SIL Open Font License 1.1, which
 * permits embedding and redistribution.
 *
 * ────────────────────────────────────────────────────────────────────
 * THE SYSTEM, AND WHY EACH FACE IS IN IT
 * ────────────────────────────────────────────────────────────────────
 * CINZEL — inscriptional Roman capitals, drawn from the letterforms
 *   cut into Roman monuments. This is the voice of a foundation stone
 *   and a museum wall, and it is what makes a page read as a sovereign
 *   institution rather than a company. Chapter numbers, the wordmark,
 *   and statements meant to be read the way an inscription is read.
 *
 * CORMORANT GARAMOND — a high-contrast Garamond of unusual delicacy.
 *   At 60pt in a light weight it is the most elegant thing available
 *   in an open licence. Chapter titles, pull quotes, hero figures.
 *
 * EB GARAMOND — a true Claude Garamond revival, and the reading voice
 *   of the book. Chosen over Cormorant for text because Cormorant's
 *   contrast, which is its glory at display size, thins to nothing at
 *   ten point.
 *
 * INTER — the technical face: labels, data, axes, tabular figures. It
 *   is deliberately neutral. In a publication set in Garamond, the
 *   sans must not compete for authority; it must be invisible and
 *   exact, and Inter's tabular numerals align in a column without
 *   being asked twice.
 */

import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import path from 'node:path';

const ROOT = path.resolve(new URL('../..', import.meta.url).pathname);
const OUT = path.join(ROOT, 'assets/fonts');

const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

/** family → the weights and styles the design actually uses. Nothing is
 *  fetched "in case", because every weight is bytes in every PDF. */
const WANT = [
  /* NEWSREADER carries the whole book: display, text and numerals. One
     superfamily across every size rather than two mismatched Garamonds,
     because its OPTICAL SIZE axis (6–72) is drawn for exactly that —
     the large sizes take the high contrast and fine terminals that make
     a title, and the small sizes thicken their hairlines so a caption
     at seven point does not disappear. Pairing Cormorant with EB
     Garamond was asking two faces to do one face's job and getting a
     display face at text size, which is why the numerals were thin. */
  { family: 'Newsreader', axis: 'opsz,ital,wght@6..72,0,300;6..72,0,400;6..72,0,500;6..72,0,600;6..72,1,300;6..72,1,400', key: 'newsreader' },
  /* ARCHIVO is the technical face: labels, data, axes, tabular figures.
     A grotesque in the Neue Haas line — neutral, precise, and with
     proper tabular numerals that hold a column without being asked
     twice. Chosen over Inter, which is the typeface of every software
     company of the last decade and reads as a product, not an
     institution. */
  { family: 'Archivo', axis: 'wght@400;500;600;700', key: 'archivo' },
];

const get = (url, binary = false) => execFileSync('curl',
  ['-sS', '-L', '-m', '40', '-H', `User-Agent: ${UA}`, url],
  { maxBuffer: 64 * 1024 * 1024, encoding: binary ? 'buffer' : 'utf8' });

function main() {
  mkdirSync(OUT, { recursive: true });
  let css = `/* GENERATED by scripts/publication/fetch-fonts.mjs — do not hand-edit.
   Four faces, latin subset, embedded base64. All SIL Open Font License 1.1.
   Cinzel and Cormorant Garamond: Copyright The Cinzel / Cormorant Project Authors.
   EB Garamond: Copyright The EB Garamond Project Authors.
   Inter: Copyright The Inter Project Authors.
   Full licence: https://scripts.sil.org/OFL */\n\n`;
  let bytes = 0;

  for (const w of WANT) {
    const url = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(w.family).replace(/%20/g, '+')}:${w.axis}&display=block`;
    const sheet = get(url);
    // Keep the latin block only. The cyrillic, greek and vietnamese
    // subsets are most of the weight and none of the document.
    const blocks = sheet.split('/*').filter((b) => /^\s*latin\s*\*\//.test(b));
    for (const b of blocks) {
      const m = b.match(/font-style:\s*(\w+);[\s\S]*?font-weight:\s*([\d ]+);[\s\S]*?src:\s*url\(([^)]+)\)/);
      if (!m) continue;
      const [, styleRaw, weightRaw, src] = m;
      const style = styleRaw; const weight = weightRaw.trim();
      const data = get(src, true);
      bytes += data.length;
      css += `@font-face{font-family:'${w.family}';font-style:${style};font-weight:${weight};font-display:block;`
        + `src:url(data:font/woff2;base64,${data.toString('base64')}) format('woff2');}\n`;
      process.stdout.write(`  ${w.family} ${style} ${weight} — ${(data.length / 1024).toFixed(0)} KB\n`);
    }
  }

  const file = path.join(OUT, 'monograph-faces.css');
  writeFileSync(file, css);
  console.log(`\nWrote ${path.relative(ROOT, file)} — ${(css.length / 1024).toFixed(0)} KB of CSS carrying ${(bytes / 1024).toFixed(0)} KB of font data.`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(new URL(import.meta.url).pathname)) main();
