/**
 * AIPC PRESS — THE HOUSE VISUAL IDENTITY.
 *
 * ────────────────────────────────────────────────────────────────────
 * WHAT A HOUSE IDENTITY IS FOR, AND WHY IT IS NOT THE SPECIFICATION
 * ────────────────────────────────────────────────────────────────────
 * The Production Specifications already describe one book exactly:
 * its trim, its stock, its ink limits, its finishing. That document is
 * measured, and everything in it is true of the flagship and of nothing
 * else. It cannot govern the second book, because it never anticipated
 * one.
 *
 * This file governs the second book. It answers the question a house
 * identity exists to answer: when a reader who owns one of our books
 * sees another on a shelf, what makes them recognise it as ours before
 * reading the title — and what makes them recognise it as a DIFFERENT
 * KIND of book without being told?
 *
 * Two systems answer that, and they must not be confused:
 *
 *   THE CONSTANTS never vary between publications. The crest, the two
 *   type families, the deep navy, the gold, the spine architecture,
 *   the folio position. These are the signature. A publication that
 *   departs from them is not a AIPC Press publication.
 *
 *   THE VARIABLES vary by publication family and only by family, along
 *   ONE axis each: format tells you the kind of book, the family colour
 *   tells you the shelf it belongs on, the cover field tells you whether
 *   it is for a learner, a teacher or an institution. One variable per
 *   distinction. Four variables carrying the same distinction is not
 *   a system, it is decoration agreeing with itself.
 *
 * ────────────────────────────────────────────────────────────────────
 * WHAT IS COMPUTED AND WHY THAT MATTERS
 * ────────────────────────────────────────────────────────────────────
 * A house identity written as prose drifts within two titles: the type
 * scale is restated slightly wrong, a colour is picked by eye from a
 * printed sample, a spine is estimated. So every number here that could
 * be derived IS derived — the trim and bleed from covers.mjs, the type
 * scale and the palettes from design.mjs, the spine from the same
 * caliper formula the flagship cover was produced with, and the family
 * colours are checked for contrast rather than asserted to be legible.
 *
 * The one thing not computed is the family assignment itself. Which hue
 * belongs to which family is a decision, and it is recorded as one.
 */
import { COLOURS, C, TYPE, BRAND, LEVEL_PALETTES } from './design.mjs';
import { TRIM, BLEED, CALIPER_MM, spineWidth } from './covers.mjs';
import { contrast } from './colour.mjs';
import { FAMILIES_IN_USE } from './catalogue.mjs';

// ─────────────────────────────────────────────────────────────────────
// 1 · THE CONSTANTS
// ─────────────────────────────────────────────────────────────────────

export const CONSTANTS = [
  ['Crest', 'The College crest, drawn as vector, appears on every front cover, every spine '
    + 'wide enough to carry it, and the title page. It is never redrawn, recoloured outside '
    + 'the two permitted treatments (gold on deep ground, single-ink on light ground), '
    + 'stretched, outlined or set inside another shape.'],
  ['Type families', `Two, and never a third: ${TYPE.serif.split(',')[0]} for continuous reading `
    + `and ${TYPE.sans.split(',')[0]} for everything scanned. A publication needing a third `
    + 'family has a structural problem the third family will not solve.'],
  ['Ground', `Deep navy ${C.midnightNavy} for covers, spines and dividers; `
    + `${C.pearlWhite} for text pages. Every publication of the Press shares both.`],
  ['Metal', `Gold ${C.royalGold} is the institutional accent and is used once per surface — `
    + 'a rule, a crest, or a title, never all three. Restraint is what makes it read as metal '
    + 'rather than as yellow.'],
  ['Folio', 'Outer edge, foot, sans, small. Same position in every publication so a reader '
    + 'flicking a book they have never opened finds the page number where their hand already is.'],
  ['Spine architecture', 'Title at the head reading downward, family mark at the foot, crest '
    + 'above it where width allows. Downward is the British and international convention; a '
    + 'shelf of our books reads consistently against neighbours.'],
  ['Verification', 'Every publication carrying credential or award content prints the '
    + 'verification QR generated by the same encoder as a graduate certificate, resolving to '
    + 'the College’s own domain. No publication prints an identifier issued by an authority '
    + 'that has not issued it.'],
];

// ─────────────────────────────────────────────────────────────────────
// 2 · FORMATS
// ─────────────────────────────────────────────────────────────────────

/**
 * Four formats, each chosen for how the book is HELD rather than how it
 * looks in a catalogue photograph. The flagship trim is taken from the
 * cover module so the two cannot diverge.
 */
export const FORMATS = [
  { key: 'flagship', name: 'Flagship', w: TRIM.w, h: TRIM.h,
    use: 'Curriculum editions, institutional volumes, the Publishing Constitution.',
    why: 'A4 portrait. It sits on an academic desk beside the paperwork it is read against, '
      + 'and it takes a full lesson — objectives through homework — on one spread.' },
  { key: 'practice', name: 'Practice', w: 176, h: 250,
    use: 'Workbooks, assessment handbooks, examination papers.',
    why: 'B5. Small enough to open flat next to a laptop, large enough that a learner can '
      + 'write in the margin. A workbook at A4 is a folder, not a book.' },
  { key: 'reference', name: 'Reference', w: 156, h: 234,
    use: 'Grammar, glossary, pronunciation, companion volumes.',
    why: 'Royal octavo. The format of a book consulted standing up, carried in a bag, and '
      + 'opened at one entry rather than read through.' },
  { key: 'scholarly', name: 'Scholarly', w: 189, h: 246,
    use: 'Journal, proceedings, monographs, annual reports.',
    why: 'The international academic serial format. A journal in a non-standard trim does not '
      + 'shelve with the literature it wants to be read beside.' },
];

export const formatFor = (key) => FORMATS.find((f) => f.key === key) || FORMATS[0];

// ─────────────────────────────────────────────────────────────────────
// 3 · THE MARGIN AND NAVIGATION SYSTEM
// ─────────────────────────────────────────────────────────────────────

/**
 * Margins as PROPORTIONS of the trim, not millimetres, so one rule
 * governs four formats. The ratios are the classical asymmetric set —
 * gutter smallest, foot largest — which puts the text block above
 * optical centre and leaves the thumb somewhere to rest.
 *
 * The gutter allowance is stated separately because it is not
 * aesthetic: it is the paper the binding eats, and it scales with
 * extent, not with trim.
 */
export const MARGINS = {
  ratios: { gutter: 0.090, head: 0.075, fore: 0.105, foot: 0.130 },
  note: 'Of trim width for gutter and fore-edge, of trim height for head and foot.',
  gutterAllowance: [
    ['Under 200 pages', 0, 'Perfect binding opens adequately; no extra allowance.'],
    ['200–400 pages', 3, 'Three millimetres added to the gutter on both sides.'],
    ['Over 400 pages', 5, 'Five millimetres, and no figure may cross the gutter at all.'],
  ],
};

/**
 * The measure ceiling exists because the margin ratios alone do not
 * produce a readable line at every format. Applied to the flagship trim
 * they yield a text block of about 89 characters — a third longer than
 * a reader can track a return sweep on — which is why the flagship
 * constrains its measure typographically, at the measure declared in
 * the type system, rather than relying on the margin. The ceiling makes that constraint part of the
 * system instead of a property of one book.
 */
MARGINS.maxMeasureChars = 75;

export function marginsFor(format, pages) {
  const f = formatFor(format);
  const extra = pages > 400 ? 5 : pages > 200 ? 3 : 0;
  const r = MARGINS.ratios;
  const gutter = round1(f.w * r.gutter + extra);
  let fore = round1(f.w * r.fore);
  const chars = (w) => Math.round(w / 1.9);
  const raw = chars(f.w - gutter - fore);
  // Widen the fore-edge until the measure is inside the ceiling. The
  // fore-edge rather than the gutter: the gutter is set by the binding.
  if (raw > MARGINS.maxMeasureChars) {
    fore = round1(f.w - gutter - MARGINS.maxMeasureChars * 1.9);
  }
  return {
    gutter,
    fore,
    head: round1(f.h * r.head),
    foot: round1(f.h * r.foot),
    measureChars: chars(f.w - gutter - fore),
    measureConstrained: raw > MARGINS.maxMeasureChars,
  };
}

const round1 = (n) => Math.round(n * 10) / 10;

export const NAVIGATION = [
  ['Running head, verso', 'The part or level. The reader’s answer to "where am I in the book".'],
  ['Running head, recto', 'The chapter, module or entry range. The answer to "where am I now".'],
  ['Running foot', 'Folio at the outer edge. Nothing else: a running foot carrying a title as '
    + 'well as a running head carrying one is the same information printed twice.'],
  ['Opener pages', 'No running head. A page that announces a section does not also need to '
    + 'label itself.'],
  ['Thumb marks', 'Reference formats only, and only where entries are alphabetical or ordered '
    + 'by level. A thumb mark on a book with no lookup order is ornament.'],
  ['Cross-references', 'Printed as level.module.lesson, never as a page number. Page numbers '
    + 'change between editions and formats; the academic reference does not.'],
];

// ─────────────────────────────────────────────────────────────────────
// 4 · THE COVER SYSTEM
// ─────────────────────────────────────────────────────────────────────

/**
 * A cover grid expressed in twelfths of the trim, so the same
 * composition holds at every format. The flagship cover already built
 * obeys it; the numbers below are what it obeys.
 */
export const COVER_GRID = [
  ['0–2/12 from head', 'Crest, centred, optically not mathematically.'],
  ['3/12', 'Institution line, letterspaced small caps, sans.'],
  ['4–7/12', 'Title field. The one place display type is permitted at cover size.'],
  ['8/12', 'Family rule — the family colour, full measure, 0.6 mm.'],
  ['9–10/12', 'Edition line: which edition of which publication, set plainly.'],
  ['11/12 to foot', 'Clear. A cover with type at the foot loses it to the shelf lip.'],
];

export const COVER_FIELDS = [
  ['Learner publications', 'Photographic field, duotone in the family colour, the crest '
    + 'reversed out. Warm, human, aspirational — the cover a learner wants to be seen '
    + 'carrying.'],
  ['Teaching publications', 'Flat deep-navy ground with the guilloché ornament at low '
    + 'contrast. Quieter than the learner cover by design: this is a working document.'],
  ['Institutional publications', 'Flat ground, no photography, gold rule only. Nothing on the '
    + 'cover that could be read as marketing.'],
  ['Scholarly publications', 'Typographic only: title, volume, issue, year. No image, no '
    + 'ornament, no colour beyond the family rule.'],
];

export const BACK_COVER = [
  ['Upper third', 'A statement of what the publication is, in three sentences. Never a claim '
    + 'the publication does not evidence inside.'],
  ['Middle', 'For learner and institutional titles: what the reader will be able to do. '
    + 'Written as capability, not as promise.'],
  ['Lower', 'Institution block, place of publication, year, edition and revision, document '
    + 'digest, verification QR.'],
  ['Barcode area', '40 × 25 mm clear at the lower fore-edge corner, reserved whether or not an '
    + 'ISBN has been assigned. Reserving it costs nothing; retrofitting it costs a redesign.'],
];

// ─────────────────────────────────────────────────────────────────────
// 5 · THE SPINE SYSTEM
// ─────────────────────────────────────────────────────────────────────

/**
 * Spine width is computed, never estimated: caliper × pages ÷ 2, from
 * the same function that produced the flagship cover artwork. What
 * changes with width is what the spine can legibly CARRY, and that is
 * a set of thresholds rather than a designer's judgement each time.
 */
export const SPINE_RULES = [
  { minMm: 0, name: 'Under 6 mm — no spine', carries: 'Saddle-stitched. There is no spine to '
    + 'print on, and the family mark moves to the front cover foot. A first draft of this table '
    + 'gave the band a typographic rule instead, which could never have fired: the spine '
    + 'calculation floors at 6 mm because a perfect-bound spine below that cannot be squared.' },
  { minMm: 6, name: '6–12 mm', carries: 'Title, family mark at the foot. Crest omitted: a crest '
    + 'under 12 mm reads as a smudge and damages the mark it is meant to establish.' },
  { minMm: 12, name: '12–20 mm', carries: 'Title, subtitle, crest at the foot, family colour '
    + 'band at the head.' },
  { minMm: 20, name: 'Over 20 mm', carries: 'Full architecture: title, subtitle, crest, family '
    + 'band, and the six level bars where the publication covers all six levels.' },
];

/**
 * The floor is not cosmetic. spineWidth() clamps at 6 mm because that
 * is the narrowest spine a perfect-bound book can be squared to; below
 * it the book is saddle-stitched and has no spine at all. The band
 * table says so rather than describing type on a surface that does not
 * exist.
 */
export function spineFor(pages) {
  const mm = spineWidth(pages);
  const rule = [...SPINE_RULES].reverse().find((r) => mm >= r.minMm);
  return { pages, mm, caliper: CALIPER_MM, bleed: BLEED, carries: rule.carries, band: rule.name };
}

// ─────────────────────────────────────────────────────────────────────
// 6 · FAMILY COLOUR
// ─────────────────────────────────────────────────────────────────────

/**
 * One hue per publication family, assigned as a decision and then
 * CHECKED. The check is the point: a family colour is printed as a rule
 * on a cover and as a band on a spine, and both carry type. A colour
 * that fails against the ground is not a family colour, it is a defect
 * that ships on every title in the family for a decade.
 *
 * The level palettes are deliberately not reused. They mean level, and
 * a family colour that also meant level would collide the moment a
 * six-level family existed.
 */
const FAMILY_HUES = {
  'IEFC Student Series': 'imperialBlue',
  'IEFC Teacher Series': 'bronze',
  'IEFC Assessment Series': 'deepCrimson',
  'IEFC Reference Library': 'richBurgundy',
  'AIPC Academic Framework Series': 'royalBlue',
  'AIPC Governance Series': 'warmCharcoal',
  'AIPC Research Series': 'slateGrey',
  'AIPC Professional Development Series': 'platinum',
  'AIPC New Programmes Series': 'champagneGold',
  'AIPC Institutional Series': 'royalGold',
};

/**
 * Three rules, and all three were broken by the first assignment made
 * by eye — which is the argument for computing them.
 *
 *   ONE COLOUR, ONE FAMILY. Two families sharing a hue means the shelf
 *   signal is decorative. The first draft gave imperial blue to two
 *   and gold to two more.
 *   THE HOUSE GROUND IS NOT A FAMILY COLOUR. Midnight navy was
 *   assigned to the Reference Library, and midnight navy on a midnight
 *   navy spine measures 1.00 : 1. It would have been invisible on the
 *   one surface the family mark exists for.
 *   EVERY FAMILY COLOUR IS PRINTED ON THE GROUND WHERE IT REACHES
 *   3 : 1, and the system says which ground that is rather than
 *   leaving it to whoever sets the next cover. Gold cannot carry a
 *   band on paper at 2.82 : 1; on navy it reaches 5.73 : 1.
 */
export function familyColours() {
  const seen = new Map();
  return FAMILIES_IN_USE.map((s) => {
    const key = FAMILY_HUES[s];
    const hex = COLOURS[key]?.hex;
    if (!hex) throw new Error(`family "${s}" has no colour assigned`);
    if (key === 'midnightNavy') throw new Error('the house ground may not be a family colour');
    if (seen.has(key)) throw new Error(`"${key}" is already the colour of "${seen.get(key)}"`);
    seen.set(key, s);
    const onPaper = round2(contrast(hex, BRAND.paper));
    const onNavy = round2(contrast(hex, C.midnightNavy));
    const ground = onPaper >= 3 ? 'paper' : onNavy >= 3 ? 'navy' : null;
    if (!ground) throw new Error(`"${key}" reaches 3:1 against neither ground`);
    return { family: s, token: key, hex, onPaper, onNavy, ground,
      ratio: ground === 'paper' ? onPaper : onNavy };
  });
}

const round2 = (n) => Math.round(n * 100) / 100;

/**
 * Where a family colour may be used, which follows from its contrast
 * rather than from taste. A hue that fails 3:1 against a ground may
 * still be a rule on that ground — a 0.6 mm line is not text — but it
 * may never carry type there.
 */
export const COLOUR_USE = [
  ['4.5:1 or better', 'May set type at any size on that ground.'],
  ['3:1 to 4.5:1', 'May set type at 14 pt and above, or bold at 11 pt. Not body text.'],
  ['Below 3:1', 'Rules, bands and fields only. Never type.'],
];

// ─────────────────────────────────────────────────────────────────────
// 7 · OPENERS, DIVIDERS, ENDPAPERS
// ─────────────────────────────────────────────────────────────────────

export const OPENERS = [
  ['Part opener', 'Full bleed, deep ground, the part numeral at display size, the part title '
    + 'below it, nothing else. Always recto; the verso before it is left blank rather than '
    + 'filled.'],
  ['Level or chapter divider', 'Photographic field in the level or family colour, the ascent '
    + 'ornament stating position in the sequence, the title, and one extracted line from the '
    + 'content itself where one exists. Never an inspirational quotation written for the page.'],
  ['Module opener', 'Half-page: rule in the family colour, module numeral, title, and the '
    + 'module’s own pull quote where the content yields one. Where it does not, the opener is '
    + 'quieter — the alternative is writing a quote, which is forgery of the curriculum’s '
    + 'voice.'],
  ['Section head', 'Text-weight. A rule, a small-caps label, and space above it that is '
    + 'twice the space below. The asymmetry is what makes it read as belonging to what '
    + 'follows.'],
];

export const ENDPAPERS = [
  ['Hardcover editions', 'Printed endpapers in the series colour at 12 % tint, carrying the '
    + 'guilloché at low contrast. Front endpaper plain; rear endpaper may carry the level or '
    + 'series map, because a reader looks there for it.'],
  ['Presentation editions', 'Solid deep navy endpapers, gold guilloché, no type.'],
  ['Paperback editions', 'None. A printed inside-cover imitating an endpaper is a hardcover '
    + 'gesture on a book that is not one.'],
];

// ─────────────────────────────────────────────────────────────────────
// 8 · FIGURES, TABLES, PHOTOGRAPHY, ICONS
// ─────────────────────────────────────────────────────────────────────

export const FIGURE_RULES = [
  ['Purpose test', 'A figure must communicate faster than the sentence it replaces. If it '
    + 'does not, it is removed rather than improved — one figure has been, and the reason is '
    + 'recorded in the source where it stood.'],
  ['Measurement', 'Every figure is rasterised and its text extracted before approval. Four '
    + 'defects in the flagship — clipped labels, overprinted text, a label running through a '
    + 'line — were invisible in the source and obvious in the raster.'],
  ['Type floor', `No text in any figure below ${TYPE.scale.micro} pt at printed size.`],
  ['Colour', 'A figure must survive greyscale. Series and level colour may distinguish, but '
    + 'never alone: shape, position or label carries the same distinction.'],
  ['Gutter', 'No figure crosses the gutter in a publication over 400 pages, and none crosses '
    + 'it in any perfect-bound publication where the crossing element carries meaning.'],
];

export const TABLE_RULES = [
  ['Rules', 'Horizontal only. A vertical rule in a table is a confession that the columns are '
    + 'not aligned.'],
  ['Header repetition', 'Table headers repeat on every page a table continues onto, set as a '
    + 'table header group so the repetition is structural rather than pasted.'],
  ['Row integrity', 'No row breaks across a page. A rubric criterion split over a spread is a '
    + 'criterion that will be misread.'],
  ['Numerals', 'Tabular lining figures in every column of numbers, aligned on the decimal.'],
  ['Totals', 'A total row states what it totals. A column of four cells under a header '
    + 'declaring five is a defect, and it has occurred once and been corrected.'],
];

export const PHOTOGRAPHY = [
  ['Licence', 'Commercially licensed, licence reference held in source, credited in the '
    + 'publication. No image is ever labelled sample or placeholder, because a publication '
    + 'containing a placeholder is not finished.'],
  ['Propriety', 'Modest, respectful and appropriate for an international Muslim-majority '
    + 'readership as well as a Western one. This is a constraint on selection, not a style, '
    + 'and it is not negotiable per publication.'],
  ['Narrative', 'Photography carries atmosphere and aspiration, never illustration of the '
    + 'obvious. A photograph of a person reading placed beside a passage about reading adds '
    + 'nothing and costs a licence.'],
  ['Treatment', 'Duotone in the level or family colour for fields and dividers; untreated at '
    + 'full colour only in plates. One treatment per publication.'],
  ['Resampling', 'Every image is resampled to its printed size at 300 ppi before placement, '
    + 'and the untouched original is kept outside version control.'],
];

export const ICONOGRAPHY = [
  ['Drawn as type', 'Stage marks are typographic glyphs, not images. They survive greyscale, '
    + 'cost nothing to embed and cannot fail to load.'],
  ['One per stage', 'A mark means one thing across every publication of the Press. A mark '
    + 'reused for a second meaning in a second book destroys its value in the first.'],
  ['Never alone', 'A mark always accompanies a word. An icon-only affordance excludes the '
    + 'reader who has not learnt the key, and the key is on a page they are not on.'],
];

// ─────────────────────────────────────────────────────────────────────
// 9 · EDITION CLASSES
// ─────────────────────────────────────────────────────────────────────

/**
 * The physical standards, stated per class rather than per title, so a
 * new publication inherits a complete specification by declaring which
 * class it belongs to. Costs are deliberately absent: they are a
 * procurement matter and would be invented here.
 */
export const EDITION_CLASSES = [
  {
    key: 'presentation', name: 'Presentation',
    paper: 'Text 120 gsm uncoated cream, FSC. Endpapers 140 gsm.',
    binding: 'Section-sewn, rounded and backed, headband, ribbon marker.',
    cover: 'Cloth over 3 mm board, foil-blocked crest and title.',
    finish: 'Gold foil, blind emboss on the crest, slipcase.',
    use: 'Ceremonial and diplomatic presentation. Never sold.',
  },
  {
    key: 'hardcover', name: 'Institutional hardcover',
    paper: 'Text 100 gsm uncoated cream, FSC.',
    binding: 'Section-sewn, square back, printed endpapers.',
    cover: 'Printed case, matt laminate, spot gloss on the crest only.',
    finish: 'No foil. Spot gloss carries the metal at a fraction of the cost.',
    use: 'Curriculum editions held in libraries and by partner institutions.',
  },
  {
    key: 'paperback', name: 'Paperback',
    paper: 'Text 90 gsm uncoated, FSC.',
    binding: 'PUR perfect binding — not EVA, which fails at this extent.',
    cover: '300 gsm one-sided board, matt laminate.',
    finish: 'None.',
    use: 'Student editions, workbooks, everything a learner carries daily.',
  },
  {
    key: 'digital', name: 'Digital',
    paper: '—',
    binding: '—',
    cover: 'Same artwork at screen resolution; spine omitted rather than faked.',
    finish: 'Tagged structure, document outline, reading order, alternative text.',
    use: 'Every publication, in parallel with its printed class.',
  },
];

export const DIGITAL_STANDARDS = [
  ['Structure', 'Tagged, with a document outline that matches the printed contents exactly. A '
    + 'digital edition whose outline disagrees with the book is two publications.'],
  ['Reading order', 'Follows the printed reading order, including apparatus. Marginal '
    + 'navigation is placed after the block it annotates, never before it.'],
  ['Alternative text', 'Every figure carries a description that states what the figure shows, '
    + 'not what it is called. "Figure 3" is not alternative text.'],
  ['Contrast', 'The printed palette is used unchanged, because it was generated against a '
    + 'contrast threshold rather than picked and then checked.'],
  ['External validation', 'PDF/UA conformance has NOT been externally validated for any '
    + 'publication of the Press. The internal checks are structural only, and the difference '
    + 'is stated rather than glossed.'],
];

// ─────────────────────────────────────────────────────────────────────
// 10 · THE SYSTEM, CHECKED
// ─────────────────────────────────────────────────────────────────────

/**
 * The house identity's own audit: the assignments that could silently
 * go wrong, recomputed. Used by the Press volume and by the tests.
 */
export function houseEvidence() {
  const colours = familyColours();
  return {
    colours,
    typeOnly: colours.filter((c) => c.onNavy >= 4.5).map((c) => c.series),
    ruleOnly: colours.filter((c) => c.onNavy < 3 && c.onPaper < 3).map((c) => c.series),
    formats: FORMATS.map((f) => ({
      ...f, margins: marginsFor(f.key, 300),
    })),
    spines: [64, 160, 320, 441].map(spineFor),
    levelBars: LEVEL_PALETTES.length,
  };
}
